// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqtOUMCYmxzC5bBDJGUqe4nNbcsZYxHgQ',
    appId: '1:279016704934:web:a659939a71c4c69e10dd67',
    messagingSenderId: '279016704934',
    projectId: 'card-game-eea6d',
    authDomain: 'card-game-eea6d.firebaseapp.com',
    storageBucket: 'card-game-eea6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj32JbbKHD2UgP8aoQRuEjkexEUzR1hXE',
    appId: '1:279016704934:android:88be1397c39d5ae110dd67',
    messagingSenderId: '279016704934',
    projectId: 'card-game-eea6d',
    storageBucket: 'card-game-eea6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6KsB6n5jsvLf2apddzFIoo2ZPbbwMbdk',
    appId: '1:279016704934:ios:3ea782755a91ada110dd67',
    messagingSenderId: '279016704934',
    projectId: 'card-game-eea6d',
    storageBucket: 'card-game-eea6d.appspot.com',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6KsB6n5jsvLf2apddzFIoo2ZPbbwMbdk',
    appId: '1:279016704934:ios:faac0650d42695f210dd67',
    messagingSenderId: '279016704934',
    projectId: 'card-game-eea6d',
    storageBucket: 'card-game-eea6d.appspot.com',
    iosBundleId: 'com.example.card.RunnerTests',
  );
}
